[package]
name = "stalwart"
version = "0.1.0"
edition = "2018"

[dependencies]
encoding_rs = {version=">=0.8.28", optional=true}
serde = { version = ">=1.0.117", features = ["derive"], optional=true}
serde_bytes = { version = ">=0.11.5", optional=true}

[dev-dependencies]
serde_yaml = ">=0.8.21"
serde_json = ">=1.0.59"

[features]
default = ["multibytedecode", "serde", "serde_bytes"]
multibytedecode = ["encoding_rs"]
