[package]
name = "stalwart"
version = "0.1.0"
edition = "2018"

[dependencies]
encoding_rs = {version=">=0.8.28", optional=true}

[features]
default = ["multibytedecode"]
multibytedecode = ["encoding_rs"]
