[package]
name = "mail-parser"
description = "Fast and robust e-mail parsing library for Rust"
version = "0.2.1"
edition = "2018"
authors = [ "Stalwart Labs <hello@stalw.art>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stalwartlabs/mail-parser"
homepage = "https://github.com/stalwartlabs/mail-parser"
keywords = ["email", "mime", "mail", "parser", "e-mail"]
categories = ["email", "parser-implementations"]
readme = "README.md"

[dependencies]
encoding_rs = {version=">=0.8.28", optional=true}
serde = { version = ">=1.0.117", features = ["derive"], optional=true}
serde_bytes = { version = ">=0.11.5", optional=true}

[dev-dependencies]
serde_yaml = ">=0.8.21"
serde_json = ">=1.0.59"

[features]
default = ["serde_support", "full_encoding"]
full_encoding = ["encoding_rs"]
serde_support = ["serde", "serde_bytes"]

[profile.bench]
debug = true
